# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Needed for backward compatibility
gems: [jekyll-paginate]

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Why Not Change the World'
tagline:          'Karls Blog'
description:      'Karls Blog'
url:              'http://mrkarl.github.io'
baseurl:          '/about'

# Navigation
navigation:
- text : About
  url : /about/
- text: Blog
  url: /blog/
- text: Technology
  url: /technology

# Author Details
author:         'Panki Park'

#Social Media links (Use complete URL except for email)
dribbble:
email:          'winnerofsky@gmail.com'
facebook:       'https://www.facebook.com/panki.park.0'
flickr:
github:         'https://github.com/mrkarl'
gplus:          
instagram:
pinterest:
linkedin:       
rss:
stackoverflow:  
twitter:        

# Google Analytics
gahandler: 

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: 'testingblogo'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.9x beta 2
